apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::087953319745:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-165NE8M7EIJ76
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-04T20:33:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1788"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fd5d8e5a-ee7c-487a-94ec-dc4bbc72e395
